server:
  port: 1111



spring:
  devtools:
    restart:
      enabled: true
  security:
#    user:
#      ?????????
#      name: admin
#      password: 123

  datasource:
    username: ENC(Qn1O39gtgEehzsMhLocucsdIrASXbWRW8/o02HLEKTQ6xswb7knPJkYKIG/LKKQY)
#    password: sasa
    password: ENC(r0F+FWGMP3mcAzF/nRWO1aPWLX/Ib1fUcX+HzEpBHirXt9CM/HRscyB1r/hWqaqW)
    # mvn jasypt:encrypt-value -Djasypt.encryptor.password=madefu -Djasypt.plugin.value=sasa
    # mvn jasypt:decrypt-value -Djasypt.encryptor.password=madefu -Djasypt.plugin.value=r0F+FWGMP3mcAzF/nRWO1aPWLX/Ib1fUcX+HzEpBHirXt9CM/HRscyB1r/hWqaqW
    # java -Djasypt.encryptor.password=madefu -jar spring-boot-application.jar
    # to Encrypt yml
      #  mvn jasypt:encrypt -Djasypt.encryptor.password=madefu -Djasypt.plugin.path=file:src/main/resources/application.yml
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver